-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "login" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'user', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "users_login_key" to table: "users"
CREATE UNIQUE INDEX "users_login_key" ON "users" ("login");
-- create index "user_login" to table: "users"
CREATE INDEX "user_login" ON "users" ("login");
