-- drop index "user_login" from table: "users"
DROP INDEX IF EXISTS "user_login";
-- create "sessions" table
CREATE TABLE "sessions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "ip_address" character varying NOT NULL, "device" character varying NOT NULL, "created_at" timestamptz NOT NULL, "user_sessions" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("user_sessions") REFERENCES "users" ("id") ON DELETE SET NULL);
