-- create "refresh_tokens" table
CREATE TABLE "refresh_tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "token" character varying NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "expires_at" timestamptz NOT NULL, "user_refresh_tokens" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "refresh_tokens_users_refresh_tokens" FOREIGN KEY ("user_refresh_tokens") REFERENCES "users" ("id") ON DELETE SET NULL);
-- create index "refresh_tokens_token_key" to table: "refresh_tokens"
CREATE UNIQUE INDEX "refresh_tokens_token_key" ON "refresh_tokens" ("token");
