events {
    worker_connections 1024;
}

http {
    server_tokens off;

  
    upstream auth_service {
        server svc-auth:8081;
    }

    upstream layers_service {
        server svc-layers:8080;
    }

    upstream features_service {
        server svc-features:8082;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/v1/auth {
            proxy_pass http://auth_service;
            

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location /api/v1/layers {
            proxy_pass http://layers_service;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/features {
            proxy_pass http://features_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}